server:
  port: 5678
  servlet:
    context-path: /location

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  application:
    name: location-service

#Spring actuator config
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: "env"

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl